path = 'C:\Users\Administrator\.espressif'
idf_path = 'C:\Users\Administrator\.espressif\v5.3.2\esp-idf'
esp_idf_json_path = 'C:\Espressif\tools\eim_idf.json'
tool_download_folder_name = 'C:\Espressif\dist'
tool_install_folder_name = 'C:\Espressif\tools'
target = ["esp32c3"]
idf_versions = ["v5.3.2"]
tools_json_file = "tools/tools.json"
config_file_save_path = "eim_config.toml"
non_interactive = true
wizard_all_questions = false
mirror = "https://dl.espressif.cn/github_assets"
idf_mirror = "https://jihulab.com/esp-mirror"
pypi_mirror = "https://pypi.mirrors.ustc.edu.cn/simple"
recurse_submodules = true
install_all_prerequisites = true
skip_prerequisites_check = false
cleanup = false
python_env_folder_name = "python"
activation_script_path_override = 'C:\Espressif\tools'
python_version_override = "python313"
create_bat_activation_script = false

[idf_features_per_version]
"v5.3.2" = ["core"]

[idf_tools_per_version]
"v5.3.2" = ["riscv32-esp-elf-gdb", "esp-clang", "riscv32-esp-elf", "cmake", "openocd-esp32", "ninja", "idf-exe", "ccache", "esp-rom-elfs"]
